---
- name: git clone pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=/usr/local/pyenv

- name: git clone virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/usr/local/pyenv/plugins/pyenv-virtualenv

- name: mkdir
  file: dest={{ item }} state=directory recurse=yes
  with_items:
    - /usr/local/pyenv/shims
    - /usr/local/pyenv/versions

- name: copy
  copy: src=pyenv.sh dest=/etc/profile.d/pyenv.sh

- name: install pyenv
  shell: |
    source ~/.bashrc
    pyenv install {{ pyenv_python_version }}
    pyenv rehash
    pyenv exec /usr/local/pyenv/shims/pip install --upgrade pip
    pyenv virtualenv {{ pyenv_python_version }} scipy-{{ pyenv_python_version }}
    pyenv global scipy-{{ pyenv_python_version }}

- name: pip install
  pip: name={{ item }} executable=/usr/local/pyenv/shims/pip
  with_items:
    - requests
    - numpy
    - pandas
    - statsmodels
    - matplotlib
    - scipy
